services:
  - type: web
    name: ai-news-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SERPER_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false 